[workspace]
members = [
  "mir-rs-sys",
  "mir-rs",
  "mir-rs/examples/mir-rs-tiling",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.85.0"
license = "GPL-2.0-or-later"
repository = "https://github.com/canonical/mir-rs"

[workspace.dependencies]
glam = "0.29"
